version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
      - "6335:6335"
    volumes:
      - ~/.knapsack/qdrant:/qdrant/storage  # Persist Qdrant data
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
  knapsack:
    build: .
    ports:
      - "8888:8888"  # Example port mapping, adjust as needed for your service
    volumes:
      - .:/app
    environment:
      - KNAPSACK_CONFIG=/app/knapsack.toml

# knapsack:
#   build:
#     context: .
#   command: python -m connectors start
#   volumes:
#     - ./path/to/python/service:/app  # Mount the service code inside the container
#   depends_on:
#     - qdrant  # Ensure Qdrant service is started first
