version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
      - "6335:6335"
    volumes:
      - ~/.knapsack/qdrant:/qdrant/storage  # Persist Qdrant data
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage

  knapsack:
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - .:/app
    depends_on:
      - qdrant
